### ISSUE TITLE
Unable to find valid certification path on BASIC-auth

### ISSUE THREAD

**Issue by ericukj** [mwtek/dashboarddataprocessor#3]
When trying to execute the "createJson" REST-call I get the following error:
```
Connection to the FHIR/Acuwave server failed:

 I/O error on GET request for "http://fhirserver.com/Observation": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

The dashboard data processor is configured to use BASIC-auth and for testing purposes I also configured a key- and trust-store. Even when importing the needed certificates the error still persists. 
Would it be possible to disable the SSL for testing purposes?

**Comment by dmeyers138** [comment]
Hey @ericukj ,
to start with the simpler problem solving: which error message do u get when using basic auth ? 
To deactivate SSL is possible for sure. The basic auth is the default setting in the yaml and its even possible to completely deactive authentication checks with setting
`auth-method: NONE`

But I'm not sure if this has really been tested intensively, so I'm happy to get feedback here.

**Comment by ericukj** [comment]
We do need to use basic auth, so setting ath-method to none wouldn't help. The error occurs already when trying to connect to our FHIR-Server no matter what kind of authentication is used.  This might be due to us using a self signed certificate. So it would be helpful to disable checking for certificates or being able to provide a trust-store regardless of which authentication method is used.

**Comment by Tim-Steinbach-UKB** [comment]
Hi @ericukj,
there are several reasons why ssl-handshake fails. In this case i think it is most likely that the certificatechain in the trust- or key-store is incorrectly constructed.

In order to exclude errors with the certificates and possibly also get more detailed error messages, i would try to test the connection of the servers with openssl.
Maybe like this for beginning
openssl s_client -connect url:port

and in detail:
openssl s_client -cert cert.crt -key key.key -CAfile Root.cer -connect url:port -state -debug

**Comment by ericukj** [comment]
The problem got resolved. The main issue seemed to be that I was using an outdated or wrong certificate.
