### ISSUE TITLE
MII Prozedur Profile

### ISSUE THREAD

**Issue by ajayheidel** [mwtek/dashboarddataprocessor#4]
The example FHIR resources do not include the general MII procedure profile given here:
https://simplifier.net/medizininformatikinitiative-modulprozeduren/sd_mii_prozedur_procedure

It is however not much different from the examples given.  My question is if a resource using this general procedure profile would be accepted by the dashboard.

**Comment by dmeyers138** [comment]
Hey @ajayheidel 
The DDP was built on the special icu related procedure resources of the [KDS ICU module](https://simplifier.net/medizininformatikinitiative-modul-intensivmedizin) and partially checks the codes of the ValueSets/CodeSystems bound there. We personally use the general procedure module in Bonn currently only for the arbitrary OPS codes. 

But this should not be a problem. The profile name is not checked for any resource, since the intention was to keep the DDP as compatible as possible with various alternative implementations (e.g. the CORD profiles). It can work with these, but it does not have to. However, the use of the KDS profiles is recommended, of course.
