### ISSUE TITLE
Switch GET queries to POST (HTTP 414)

### ISSUE THREAD

**Issue by FloSeidel** [mwtek/dashboarddataprocessor#7]
Since we have a lot of resources in our FHIR Store the GET queries are getting too long. Our Reverse Proxy (nginx) are blocking the request with a HTTP Error Code 414 ("Request-URI Too Large").

logs:
```
dashboard-data-processor  | 2023-11-07 10:18:55.173  INFO 1 --- [nio-9091-exec-8] d.u.m.d.CoronaDashboardApplication       : Retrieving Patient data: 0/<a_lot_of>patients
dashboard-data-processor  | 2023-11-07 10:18:55.225 ERROR 1 --- [nio-9091-exec-8] d.u.m.d.CoronaDashboardApplication       : Workflow aborted: 414 Request-URI Too Large: "<html><EOL><EOL><head><title>414 Request-URI Too Large</title></head><EOL><EOL><body><EOL><EOL><center><h1>414 Request-URI Too Large</h1></center><EOL><EOL><hr><center>nginx/1.25.1</center><EOL><EOL></body><EOL><EOL></html><EOL><EOL>"
```

The workaround would be to alter the configuration of the reverse proxy (altough I'm not sure if the FHIR Store wouldn't throw the error itself). 

The correct solution (imho) would be to change the requests to a POST request (which would put the search parameters in the body).
https://www.hl7.org/fhir/search.html#transportprotocols

**Comment by dmeyers138** [comment]
Hey @FloSeidel ,

we deliberately decided to use simple GET operations in order to be able to recognize directly from the sent URLs which queries go out and also to be able to simply encapsulate them and send them to the FHIR server as a single query. 

Have you already tried to reduce the number of IDs passed (_batchsize_) in the YAML ? 

`  
fhir:
## Adjustment of FHIR search requests on the FHIR server
  search:
    ## Batch size of the parallelized partial FHIR searches
    batchsize: 50`

**Comment by FloSeidel** [comment]
Hi @dmeyers138 ,

thanks! I understand!
Altering the batchsize fixed my issue.
