### ISSUE TITLE
max-count-size greift nicht bei FHIR-Search der Patienten

### ISSUE THREAD

**Issue by wendtt** [mwtek/dashboarddataprocessor#8]
In der Konfiguration der Software per application.yaml greifen offenbar die beiden Parameter „max-count-size“ nicht konsequent bei allen Abfragen. Bei der Abfrage der Patienten selbst werden die in einem Aufruf von …/fhir/Patient?_id=… übergebenen ID-Listen sehr  lang. Unser FHIR-Server steigt dann mit einem Fehler aus und im Log des FHIR-Servers steht ein expliziter Hinweis auf den zu großen GET-Header.
Mit einer (inhaltlich natürlich nicht sinnvollen) Anpassung der Parameter in application.yaml zur Reduzierung der berücksichtigten Diagnosen und PCR-Codes konnten wir eine hinreichend kleine Patientenkohorte für einen erfolgreichen Durchlauf definieren. Auch dann überstieg die Anzahl der Patienten-Ressourcen-IDs in der FHIR-Search-Abfrage die Anzahl in max-count-size.
FHIR-Server: HAPI-Referenzimplementierung Version 6.10.0

**Comment by dmeyers138** [comment]
Hello @wendtt 
the count parameter (and thus the max-count-size) afaik only has an influence on the output of the FHIR search query, namely on the number of resources to be returned. (More [here](https://hapifhir.io/hapi-fhir/docs/server_plain/rest_operations_search.html#limiting-results)). 
The value is set to an unreachable value by default so that no resources are left behind, but needed since some fhir servers got low defaults here and theres no paging implemented (yet).

You mentioned "both parameters", is the "batchsize" parameter meant as the second parameter? 
If not, please lower it and try again. Maybe this it exactly what you are looking for. 
It explicitly limits the number of IDs that are queried per request. 
I just tested it again with a HAPI and the patient and encounter queries were nested accordingly. (tested the newest 0.5.0-alpha1 version)

If possible, set the log level to DEBUG for the de.ukbonn.mwtek.dashboard package beforehand, if not already done, then the FHIR search queries sent will also be displayed in the console.

**Comment by wendtt** [comment]
Thank you for the hint about the parameter batchsize.

I reset the two max-count-size parameterst o the original value and lowered the batchsize parameter. Now the DDP seems to run successfully.
I recommend to adjust the comments about the meaning of the parameters in application.yaml. Especially the two max-count-size parameters may be misunderstood.

Thank you for your help,
Kind regards,
Thomas

Von: David Meyers ***@***.***>
Gesendet: Mittwoch, 3. Januar 2024 15:47
An: mwtek/dashboarddataprocessor ***@***.***>
Cc: Wendt, Thomas ***@***.***>; Mention ***@***.***>
Betreff: Re: [mwtek/dashboarddataprocessor] max-count-size greift nicht bei FHIR-Search der Patienten (Issue #8)

WARNUNG: Diese E-Mail kam von außerhalb der Organisation. Klicken Sie nicht auf Links oder öffnen Sie keine Anhänge, es sei denn, Sie kennen den Absender und wissen, dass der Inhalt sicher ist.


Hello @wendtt<https://github.com/wendtt>
the count parameter (and thus the max-count-size) afaik only has an influence on the output of the FHIR search query, namely on the number of resources to be returned. (More here<https://hapifhir.io/hapi-fhir/docs/server_plain/rest_operations_search.html#limiting-results>).
The value is set to an unreachable value by default so that no resources are left behind, but needed since some fhir servers got low defaults here and theres no paging implemented (yet).

You mentioned "both parameters", is the "batchsize" parameter meant as the second parameter?
If not, please lower it and try again. Maybe this it exactly what you are looking for.
It explicitly limits the number of IDs that are queried per request.
I just tested it again with a HAPI and the patient and encounter queries were nested accordingly. (tested the newest 0.5.0-alpha1 version)

If possible, set the log level to DEBUG for the de.ukbonn.mwtek.dashboard package beforehand, if not already done, then the FHIR search queries sent will also be displayed in the console.

**Comment by dmeyers138** [comment]
Will improve the documentation there, thanks for the feedback.
